# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import time
from selenium.webdriver.common.by import By
from selenium import webdriver
from bs4 import BeautifulSoup
import lxml
import json
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(352, 619)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(-5, 1, 361, 491))
        self.listWidget.setObjectName("listWidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 490, 351, 121))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.btnfunc()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Обновить"))
    def parsingvalut(self):
        url = 'https://myfin.by/crypto-rates'
        options = webdriver.ChromeOptions()
        options.headless = True
        driver = webdriver.Chrome(executable_path='chromedriver.exe', options=options)
        try:
            driver.get(url=url)
            time.sleep(5)
            print('Зашёл на страницу')
            html_page = driver.page_source
            with open('htmlpage.html', 'w+') as file:
                file.write(html_page)

        except Exception:
            print(Exception)

        finally:
            driver.close()
            driver.quit()

        currency = []
        with open('htmlpage.html', 'r') as file:
            htmlpg = file.read()

        soup = BeautifulSoup(htmlpg, 'lxml')
        all_currency = soup.find('tbody', class_='table-body')
        currency1 = soup.find_all('tr', class_='odd')
        for c1 in currency1:
            name = c1.find('a', class_='s-bold').text
            price = c1.find('div', class_='crypto_iname hidden-xs').find_next('td').text
            capitalistic = c1.find('td', class_='hidden-xs').text
            currency.append({
                'name': name,
                'price': price,
                'capital': capitalistic
            })

        with open('donecurrency.json', 'w', encoding='utf8') as file:
            json.dump(currency, file, indent=4, ensure_ascii=False)

    def btnfunc(self):
        self.pushButton.clicked.connect(self.btnpb)

    def btnpb(self):

        self.parsingvalut()
        self.listWidget.clear()
        with open('donecurrency.json', 'r', encoding='utf8') as file:
          itml = json.load(file)

        for item in itml:
            name = item.get('name')
            price = item.get('price')
            capital = item.get('capital')
            self.listWidget.addItem(f"{name} - {price} - {capital}")




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
